/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: a1fFQhwqi4XTCQmGu8QoR6

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsgc0CMkxnOq2 } from "./afr/PlasmicGlobalVariant__Screen"; // plasmic-import: Gc0-cMkxnOq2/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsgc0CMkxnOq2
});
