/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: a1fFQhwqi4XTCQmGu8QoR6
// Component: hMLhqYxg1-pc

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: Unvo_VN2sLgt/component
import Footer from "../../Footer"; // plasmic-import: 94q9n4Vyej7p/component
import { _useGlobalVariants } from "../plasmic-init"; // plasmic-import: a1fFQhwqi4XTCQmGu8QoR6/projectModule
import { _useStyleTokens } from "../plasmic-style-tokens"; // plasmic-import: a1fFQhwqi4XTCQmGu8QoR6/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../plasmic.module.css"; // plasmic-import: a1fFQhwqi4XTCQmGu8QoR6/projectcss
import sty from "./PlasmicLicensing.module.css"; // plasmic-import: hMLhqYxg1-pc/css

createPlasmicElementProxy;

export type PlasmicLicensing__VariantMembers = {};
export type PlasmicLicensing__VariantsArgs = {};
type VariantPropType = keyof PlasmicLicensing__VariantsArgs;
export const PlasmicLicensing__VariantProps = new Array<VariantPropType>();

export type PlasmicLicensing__ArgsType = {};
type ArgPropType = keyof PlasmicLicensing__ArgsType;
export const PlasmicLicensing__ArgProps = new Array<ArgPropType>();

export type PlasmicLicensing__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<typeof Header>;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultLicensingProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLicensing__RenderFunc(props: {
  variants: PlasmicLicensing__VariantsArgs;
  args: PlasmicLicensing__ArgsType;
  overrides: PlasmicLicensing__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicLicensing.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicLicensing.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={PlasmicLicensing.pageMetadata.title}
        />
        <meta
          key="description"
          property="description"
          content={PlasmicLicensing.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicLicensing.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          property="twitter:description"
          content={PlasmicLicensing.pageMetadata.description}
        />
        <meta
          key="og:image"
          property="og:image"
          content={PlasmicLicensing.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={PlasmicLicensing.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            className={classNames(
              projectcss.all,
              sty.freeBox__nuxXf,
              "hero-image-fade"
            )}
          >
            <Header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames("__wab_instance", sty.header)}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__mzMvS)}>
            <div className={classNames(projectcss.all, sty.freeBox__gFmCy)}>
              <div className={classNames(projectcss.all, sty.columns__unc2J)}>
                <div className={classNames(projectcss.all, sty.column__dw1Ce)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__fo0HA
                    )}
                  >
                    {"Select placements. \nSerious rights hygiene."}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rU6
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {
                          "Angelfish Records is a boutique label built for clean licensing: controlled rights, canonical metadata, and disciplined approvals. We take on a limited number of placements and prioritise context, fit, and creative integrity over volume. \n\nWe operate with an artist-first philosophy aligned with the "
                        }
                      </React.Fragment>
                      {
                        <PlasmicLink__
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.link___5Rnx
                          )}
                          component={Link}
                          href={"https://winformusic.org/fair-digital-deals/"}
                          platform={"nextjs"}
                        >
                          {"WIN Fair Digital Deals Declaration"}
                        </PlasmicLink__>
                      }
                      <React.Fragment>
                        {
                          ", prioritising fair terms, clarity, and long-term creative partnerships.\n\nContact: "
                        }
                      </React.Fragment>
                      {
                        <PlasmicLink__
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.link__xTwy8
                          )}
                          component={Link}
                          href={"mailto:licensing@angelfishrecords.com"}
                          platform={"nextjs"}
                        >
                          {"licensing@angelfishrecords.com"}
                        </PlasmicLink__>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column___17R9L)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__aScfx)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"747px"}
                    loader={"plasmic"}
                    loading={"lazy"}
                    src={{
                      src: "https://img.plasmic.app/img-optimizer/v1/img/69f1ce7a3734a366b24b73384d6630ad.png",
                      fullWidth: 2670,
                      fullHeight: 1198
                    }}
                  />
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___7SXly)}>
            <div className={classNames(projectcss.all, sty.freeBox__fg7P9)}>
              <div className={classNames(projectcss.all, sty.columns___1DMvp)}>
                <div className={classNames(projectcss.all, sty.column__wZz2J)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__abx0Y
                    )}
                  >
                    {"Editorial use policy"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pqXg
                    )}
                  >
                    {
                      "We welcome cultural, editorial, and critical uses of Angelfish Records works, including the use of clips or excerpts where the music itself is the focus of discussion, analysis, review, or documentation. Such uses are permitted even where the surrounding content is monetised through platform advertising or subscriptions. Our default posture is non-adversarial: we do not treat these uses as infringement, and we aim to avoid disruptive claims or takedowns. This permission does not cover use of our music as background or soundtrack for unrelated content, commercial promotion, or brand activity. All other uses require a licence.\n\nWhere fingerprinting systems generate automatic claims, our policy is to resolve conflicts promptly and to maintain whitelisting where feasible. If your upload is blocked or claimed in a way that conflicts with this policy, contact us with the video link and we\u2019ll address it.\n"
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__w2HKp)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__oyjOd
                    )}
                  >
                    {"Working with us"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pt5Wm
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {
                          "We consider sync for film, television, games, advertising, fashion, trailers, and immersive work. If you\u2019re reaching out with a brief, include medium, term, territory, context, and whether you need master-only or full sync. We\u2019ll respond with availability and next steps. For supervisors and agencies, we can supply a concise pack with rights status per track, identifier snapshots, and a curated selection of listening links.\n\n"
                        }
                      </React.Fragment>
                      {
                        <PlasmicLink__
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.link__diZ5R
                          )}
                          component={Link}
                          href={
                            "mailto:licensing@angelfishrecords.com?subject=Supervisor%20Pack%20Request&body=Hi%20team%2C%0D%0A%0D%0AI%20would%20like%20to%20request%20a%20supervisor%20pack.%0D%0A%0D%0AProject%20%2F%20outlet%3A%0D%0AIntended%20use%20or%20context%3A%0D%0ATerritory%20%2F%20timeframe%3A%0D%0AContact%20name%20%2F%20phone%3A%0D%0A"
                          }
                          platform={"nextjs"}
                        >
                          {"Request a supervisor pack."}
                        </PlasmicLink__>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__ei9TX)}>
            <div className={classNames(projectcss.all, sty.freeBox__eWwmf)}>
              <div className={classNames(projectcss.all, sty.freeBox__ct3R5)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___1SBsB)}
                  displayHeight={"48px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loader={"plasmic"}
                  src={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/2fcada28cf93910c09e38e74ac020aa8.png",
                    fullWidth: 1208,
                    fullHeight: 439
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__pgxTu)}
                  displayHeight={"48px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loader={"plasmic"}
                  src={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/d171d73697f818b902870d47b65c2b2e.png",
                    fullWidth: 661,
                    fullHeight: 823
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__lojiI)}
                  displayHeight={"48px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loader={"plasmic"}
                  src={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/1e978e99fe53485f8f5577e71440e396.png",
                    fullWidth: 800,
                    fullHeight: 629
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__xjIwu)}
                  displayHeight={"48px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loader={"plasmic"}
                  src={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/03fc71924595fc416f3663e2537ed1dc.png",
                    fullWidth: 445,
                    fullHeight: 352
                  }}
                />
              </div>
            </div>
          </div>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "footer"],
  header: ["header"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLicensing__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLicensing__VariantsArgs;
    args?: PlasmicLicensing__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLicensing__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLicensing__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLicensing__ArgProps,
          internalVariantPropNames: PlasmicLicensing__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLicensing__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLicensing";
  } else {
    func.displayName = `PlasmicLicensing.${nodeName}`;
  }
  return func;
}

export const PlasmicLicensing = Object.assign(
  // Top-level PlasmicLicensing renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicLicensing
    internalVariantProps: PlasmicLicensing__VariantProps,
    internalArgProps: PlasmicLicensing__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Angelfish Records",
      description:
        "Official website of Angelfish Records, an independent label founded in 2026 in Aotearoa New Zealand.",
      ogImageSrc:
        "https://site-assets.plasmic.app/1ccadf233a844c04b10707e10966fe55.png",
      canonical: ""
    }
  }
);

export default PlasmicLicensing;
/* prettier-ignore-end */
