/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: a1fFQhwqi4XTCQmGu8QoR6
// Component: mzzSfoGytsXP

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: Unvo_VN2sLgt/component
import Footer from "../../Footer"; // plasmic-import: 94q9n4Vyej7p/component
import { _useGlobalVariants } from "../plasmic-init"; // plasmic-import: a1fFQhwqi4XTCQmGu8QoR6/projectModule
import { _useStyleTokens } from "../plasmic-style-tokens"; // plasmic-import: a1fFQhwqi4XTCQmGu8QoR6/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../plasmic.module.css"; // plasmic-import: a1fFQhwqi4XTCQmGu8QoR6/projectcss
import sty from "./PlasmicArtists.module.css"; // plasmic-import: mzzSfoGytsXP/css

import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: JxeaX-l3zJ-R/icon

createPlasmicElementProxy;

export type PlasmicArtists__VariantMembers = {};
export type PlasmicArtists__VariantsArgs = {};
type VariantPropType = keyof PlasmicArtists__VariantsArgs;
export const PlasmicArtists__VariantProps = new Array<VariantPropType>();

export type PlasmicArtists__ArgsType = {};
type ArgPropType = keyof PlasmicArtists__ArgsType;
export const PlasmicArtists__ArgProps = new Array<ArgPropType>();

export type PlasmicArtists__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<typeof Header>;
  section?: Flex__<"section">;
  foreground3?: Flex__<"div">;
  svg?: Flex__<"svg">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultArtistsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicArtists__RenderFunc(props: {
  variants: PlasmicArtists__VariantsArgs;
  args: PlasmicArtists__ArgsType;
  overrides: PlasmicArtists__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicArtists.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicArtists.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={PlasmicArtists.pageMetadata.title}
        />
        <meta
          key="description"
          property="description"
          content={PlasmicArtists.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicArtists.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          property="twitter:description"
          content={PlasmicArtists.pageMetadata.description}
        />
        <meta
          key="og:image"
          property="og:image"
          content={PlasmicArtists.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={PlasmicArtists.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            className={classNames(
              projectcss.all,
              sty.freeBox__sPj6I,
              "hero-image-fade"
            )}
          >
            <Header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames("__wab_instance", sty.header)}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___07Bi6)}>
            <div className={classNames(projectcss.all, sty.freeBox__qybh6)}>
              <div className={classNames(projectcss.all, sty.freeBox__tvs0H)}>
                <section
                  data-plasmic-name={"section"}
                  data-plasmic-override={overrides.section}
                  className={classNames(projectcss.all, sty.section)}
                >
                  <div
                    data-plasmic-name={"foreground3"}
                    data-plasmic-override={overrides.foreground3}
                    className={classNames(projectcss.all, sty.foreground3)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___4MrcX
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__kJqGh
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__oYdRi
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__x737W
                            )}
                          >
                            <PlasmicLink__
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                sty.link__yUbX
                              )}
                              component={Link}
                              href={"https://www.brendanjohnroch.com"}
                              platform={"nextjs"}
                              target={"_blank"}
                            >
                              <PlasmicImg__
                                alt={""}
                                className={classNames(sty.img__cf5Jb)}
                                displayHeight={"auto"}
                                displayMaxHeight={"none"}
                                displayMaxWidth={"100%"}
                                displayMinHeight={"0"}
                                displayMinWidth={"0"}
                                displayWidth={"340px"}
                                loader={"plasmic"}
                                loading={"lazy"}
                                onClick={async event => {
                                  const $steps = {};
                                }}
                                src={{
                                  src: "https://img.plasmic.app/img-optimizer/v1/img/7167a076b50e3f36f2bf49e5d44d6896.png",
                                  fullWidth: 870,
                                  fullHeight: 870
                                }}
                              />
                            </PlasmicLink__>
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__zHqJc
                              )}
                            >
                              <Icon8Icon
                                data-plasmic-name={"svg"}
                                data-plasmic-override={overrides.svg}
                                className={classNames(projectcss.all, sty.svg)}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                        </div>
                      </div>
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__xi1B
                      )}
                      component={Link}
                      href={"https://www.brendanjohnroch.com"}
                      platform={"nextjs"}
                      target={"_blank"}
                    >
                      {"BJR"}
                    </PlasmicLink__>
                  </div>
                </section>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___5QTjH)}>
            <div className={classNames(projectcss.all, sty.freeBox__l6VMm)}>
              <div className={classNames(projectcss.all, sty.freeBox__eMfgF)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__emvNi)}
                  displayHeight={"48px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loader={"plasmic"}
                  src={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/2fcada28cf93910c09e38e74ac020aa8.png",
                    fullWidth: 1208,
                    fullHeight: 439
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___148Af)}
                  displayHeight={"48px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loader={"plasmic"}
                  src={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/d171d73697f818b902870d47b65c2b2e.png",
                    fullWidth: 661,
                    fullHeight: 823
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__rmkSe)}
                  displayHeight={"48px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loader={"plasmic"}
                  src={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/1e978e99fe53485f8f5577e71440e396.png",
                    fullWidth: 800,
                    fullHeight: 629
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__bsoEn)}
                  displayHeight={"48px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loader={"plasmic"}
                  src={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/03fc71924595fc416f3663e2537ed1dc.png",
                    fullWidth: 445,
                    fullHeight: 352
                  }}
                />
              </div>
            </div>
          </div>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "section", "foreground3", "svg", "footer"],
  header: ["header"],
  section: ["section", "foreground3", "svg"],
  foreground3: ["foreground3", "svg"],
  svg: ["svg"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  section: "section";
  foreground3: "div";
  svg: "svg";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicArtists__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicArtists__VariantsArgs;
    args?: PlasmicArtists__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicArtists__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicArtists__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicArtists__ArgProps,
          internalVariantPropNames: PlasmicArtists__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicArtists__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicArtists";
  } else {
    func.displayName = `PlasmicArtists.${nodeName}`;
  }
  return func;
}

export const PlasmicArtists = Object.assign(
  // Top-level PlasmicArtists renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    section: makeNodeComponent("section"),
    foreground3: makeNodeComponent("foreground3"),
    svg: makeNodeComponent("svg"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicArtists
    internalVariantProps: PlasmicArtists__VariantProps,
    internalArgProps: PlasmicArtists__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Angelfish Records",
      description:
        "Official website of Angelfish Records, an independent label founded in 2026 in Aotearoa New Zealand.",
      ogImageSrc:
        "https://site-assets.plasmic.app/1ccadf233a844c04b10707e10966fe55.png",
      canonical: ""
    }
  }
);

export default PlasmicArtists;
/* prettier-ignore-end */
